# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\QT PR\GameWidget\ShipListWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShipListWidget(object):
    def setupUi(self, ShipListWidget):
        ShipListWidget.setObjectName("ShipListWidget")
        ShipListWidget.resize(588, 169)
        self.gridLayout = QtWidgets.QGridLayout(ShipListWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(ShipListWidget)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setLineWidth(0)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)

        self.retranslateUi(ShipListWidget)
        QtCore.QMetaObject.connectSlotsByName(ShipListWidget)

    def retranslateUi(self, ShipListWidget):
        _translate = QtCore.QCoreApplication.translate
        ShipListWidget.setWindowTitle(_translate("ShipListWidget", "ShipListWidget"))
