# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Git\sea_battle\src\Presenter\GameArea.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameArea(object):
    def setupUi(self, GameArea):
        GameArea.setObjectName("GameArea")
        GameArea.resize(800, 600)
        GameArea.setAcceptDrops(False)
        self.gridLayout = QtWidgets.QGridLayout(GameArea)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(GameArea)
        self.graphicsView.setStyleSheet("background: transparent")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView.setLineWidth(0)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)

        self.retranslateUi(GameArea)
        QtCore.QMetaObject.connectSlotsByName(GameArea)

    def retranslateUi(self, GameArea):
        _translate = QtCore.QCoreApplication.translate
        GameArea.setWindowTitle(_translate("GameArea", "GameWidget"))
