# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gamewindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def setupUi(self, GameWindow):
        GameWindow.setObjectName("GameWindow")
        GameWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GameWindow.sizePolicy().hasHeightForWidth())
        GameWindow.setSizePolicy(sizePolicy)
        GameWindow.setMinimumSize(QtCore.QSize(1000, 600))
        GameWindow.setMaximumSize(QtCore.QSize(1000, 600))
        GameWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(GameWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wigdet_player_1 = QtWidgets.QWidget(self.centralwidget)
        self.wigdet_player_1.setObjectName("wigdet_player_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wigdet_player_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_player_1 = QtWidgets.QLabel(self.wigdet_player_1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_player_1.setFont(font)
        self.label_player_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_player_1.setObjectName("label_player_1")
        self.verticalLayout.addWidget(self.label_player_1)
        self.game_area_1 = GameWidget(self.wigdet_player_1)
        self.game_area_1.setObjectName("game_area_1")
        self.verticalLayout.addWidget(self.game_area_1)
        self.ships_list_1 = ShipListWidget(self.wigdet_player_1)
        self.ships_list_1.setObjectName("ships_list_1")
        self.verticalLayout.addWidget(self.ships_list_1)
        self.verticalLayout.setStretch(1, 9)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addWidget(self.wigdet_player_1)
        self.wigdet_player_2 = QtWidgets.QWidget(self.centralwidget)
        self.wigdet_player_2.setObjectName("wigdet_player_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wigdet_player_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_player_2 = QtWidgets.QLabel(self.wigdet_player_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_player_2.setFont(font)
        self.label_player_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_player_2.setObjectName("label_player_2")
        self.verticalLayout_2.addWidget(self.label_player_2)
        self.game_area_2 = GameWidget(self.wigdet_player_2)
        self.game_area_2.setObjectName("game_area_2")
        self.verticalLayout_2.addWidget(self.game_area_2)
        self.ships_list_2 = ShipListWidget(self.wigdet_player_2)
        self.ships_list_2.setObjectName("ships_list_2")
        self.verticalLayout_2.addWidget(self.ships_list_2)
        self.verticalLayout_2.setStretch(1, 9)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.addWidget(self.wigdet_player_2)
        GameWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GameWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        GameWindow.setMenuBar(self.menubar)
        self.actionPreparePlayer_1 = QtWidgets.QAction(GameWindow)
        self.actionPreparePlayer_1.setObjectName("actionPreparePlayer_1")
        self.actionPreparePlayer_2 = QtWidgets.QAction(GameWindow)
        self.actionPreparePlayer_2.setObjectName("actionPreparePlayer_2")
        self.actionPlayer_1 = QtWidgets.QAction(GameWindow)
        self.actionPlayer_1.setObjectName("actionPlayer_1")
        self.actionPlayer_2 = QtWidgets.QAction(GameWindow)
        self.actionPlayer_2.setObjectName("actionPlayer_2")
        self.menu.addAction(self.actionPreparePlayer_1)
        self.menu.addAction(self.actionPreparePlayer_2)
        self.menu.addAction(self.actionPlayer_1)
        self.menu.addAction(self.actionPlayer_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(GameWindow)
        QtCore.QMetaObject.connectSlotsByName(GameWindow)

    def retranslateUi(self, GameWindow):
        _translate = QtCore.QCoreApplication.translate
        GameWindow.setWindowTitle(_translate("GameWindow", "Sea battle"))
        self.label_player_1.setText(_translate("GameWindow", "Player 1"))
        self.label_player_2.setText(_translate("GameWindow", "Player 2"))
        self.menu.setTitle(_translate("GameWindow", "Menu"))
        self.actionPreparePlayer_1.setText(_translate("GameWindow", "Prepare player 1"))
        self.actionPreparePlayer_2.setText(_translate("GameWindow", "Prepare player 2"))
        self.actionPlayer_1.setText(_translate("GameWindow", "Player 1"))
        self.actionPlayer_2.setText(_translate("GameWindow", "Player 2"))
from view.GameWidget import GameWidget
from view.ShipListWidget import ShipListWidget
